config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.urls import path
from .views import post_list, post_detail, post_create, post_update, post_delete, PostListView, PostDetailView, \
    PostCreateView, PostUpdateView, PostDeleteView

app_name = 'crud'

urlpatterns = [
    path('', PostListView.as_view(), name="post-list"),
    path('post/<int:id>/', PostDetailView.as_view(), name='post-detail'),
    path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:id>/edit/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:id>/delete/', PostDeleteView.as_view(), name='post-delete')
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.contrib.auth.models import BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Email required")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    username = models.CharField(max_length=100, unique=True, default="")
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.username

crud/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='post_images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def get_absolute_url(self):
        return reverse('crud:post-detail', kwargs={'id': self.id})


    def __str__(self):
        return self.title

crud/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description", "image"]

        widgets = {
            "title": forms.TextInput(attrs={
                "class": "w-full px-4 py-2 border rounded-lg"
            }),
            "description": forms.Textarea(attrs={
                "class": "w-full px-4 py-2 border rounded-lg",
                "rows": 5
            }),
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post
from .forms import PostForm

# CBV PostListView
class PostListView(ListView):
    model = Post
    template_name = 'crud/post_list.html'
    context_object_name = 'posts'
    ordering = '-created_at'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['title'] = 'All posts'
        return context

# FBV
def post_list(request):
    posts = Post.objects.all()
    context = {'posts':posts}
    return render(request, 'crud/post_list.html', context)

# CBV PostDetailView
class PostDetailView(DetailView):
    model = Post
    template_name = 'crud/post_detail.html'
    context_object_name = 'post'
    pk_url_kwarg = 'id'

# FBV
def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    context = {'post':post}
    return render(request, 'crud/post_detail.html', context)

# CBV PostCreateView
class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'description', 'image']
    template_name = 'crud/post_create.html'
    success_url = reverse_lazy('post-list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

# FBV
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(post.get_absolute_url())
    form = PostForm()
    return render(request, 'crud/post_create.html', {'form':form})


# CBV PostUpdateView
class PostUpdateView(UpdateView):
    model = Post
    template_name = 'crud/post_update.html'
    context_object_name = 'post'
    fields = ['title', 'description', 'image']
    pk_url_kwarg = 'id'

    def get_success_url(self):
        return self.object.get_absolute_url()

def post_update(request, id):
    post = get_object_or_404(Post, id=id)

    if post.author != request.user:
        return redirect('post-list')
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(post.get_absolute_url())
    form = PostForm(instance=post)
    return render(request, 'crud/post_update.html', {'form':form, 'post':post})


# CBV PostDelete
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'crud/warning.html'
    context_object_name = 'post'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('post-list')

    def test_func(self):
        post = self.get_object()
        return post.author == self.request.user

@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)

    if post.author != request.user:
        return redirect('post-list')
    
    if request.method == 'POST':
        post.delete()
        return redirect('post-list')
    return render(request, 'crud/warning.html', {'post':post})

crud/templates/crud/base.html
<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />

		<title>{% block title %}CRUD App{% endblock %}</title>

		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="" />
		<script src="https://cdn.tailwindcss.com"></script>
		<style>
			@keyframes gradient {
				0% {
					background-position: 0% 50%;
				}
				50% {
					background-position: 100% 50%;
				}
				100% {
					background-position: 0% 50%;
				}
			}
		</style>
	</head>
	<body
		class="min-h-screen bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 bg-[length:400%_400%] animate-[gradient_10s_ease_infinite]"
	>
		<header class="bg-white shadow-md sticky top-0 z-50">
			<div class="max-w-7xl mx-auto px-6">
				<div class="flex justify-between items-center h-16">
					<!-- Logo -->
					<div class="text-2xl font-bold text-indigo-600">PostBlog</div>

					<!-- Desktop Menu -->
					<nav class="hidden md:flex space-x-8 font-medium text-gray-700">
						<a
							href="{% url 'crud:post-list' %}"
							class="hover:text-indigo-600 transition"
							>Home</a
						>
						<a
							href="{% url 'crud:post-create' %}"
							class="hover:text-indigo-600 transition"
							>Create</a
						>
						<a href="#" class="hover:text-indigo-600 transition">Services</a>
						<a href="#" class="hover:text-indigo-600 transition">Blog</a>
						<a href="#" class="hover:text-indigo-600 transition">Contact</a>
					</nav>

					<!-- CTA Button -->
					<div class="hidden md:block">
						<a
							href=""
							class="px-5 py-2 rounded-lg bg-gradient-to-r from-indigo-500 to-purple-600 text-white font-semibold shadow-md hover:opacity-90 transition"
						>
              {% if request.user.is_authenticated %}
							{{ request.user }}
                {% else %}
                register
              {% endif %}
						</a>
					</div>

					<!-- Mobile Button -->
					<button
						id="menu-btn"
						class="md:hidden text-gray-700 focus:outline-none"
					>
						<svg
							xmlns="http://www.w3.org/2000/svg"
							class="h-7 w-7"
							fill="none"
							viewBox="0 0 24 24"
							stroke="currentColor"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M4 6h16M4 12h16M4 18h16"
							/>
						</svg>
					</button>
				</div>
			</div>

			<!-- Mobile Menu -->
			<div
				id="mobile-menu"
				class="hidden md:hidden border-t bg-gradient-to-r from-blue-500 to-transparent"
			>
				<nav
					class="flex flex-col px-6 py-4 space-y-3 font-medium text-gray-700"
				>
					<a href="{% url 'crud:post-list' %}" class="hover:text-indigo-600">Home</a>
					<a href="{% url 'crud:post-create' %}" class="hover:text-indigo-600"
						>Create</a
					>
					<a href="#" class="hover:text-indigo-600">Services</a>
					<a href="#" class="hover:text-indigo-600">Blog</a>
					<a href="#" class="hover:text-indigo-600">Contact</a>
					<a
						href="#"
						class="mt-3 text-center px-4 py-2 rounded-lg bg-indigo-600 text-white"
					>
						Get Started
					</a>
				</nav>
			</div>
		</header>
		{% block content %} {% endblock %}

		<script src="" async defer></script>
		<script>
			const btn = document.getElementById("menu-btn");
			const menu = document.getElementById("mobile-menu");

			btn.addEventListener("click", () => {
				menu.classList.toggle("hidden");
			});
		</script>
	</body>
</html>

crud/templates/crud/post_create.html
{% extends "crud/base.html" %} {% block title %}Post Create{% endblock %}
{% load static %}
{%block content %}
<div class="min-h-screen py-12">
	<div class="max-w-7xl mx-auto px-6">
		<div class="bg-gray-100 rounded-3xl shadow-xl p-8">
			<form method="post" enctype="multipart/form-data" class="space-y-6">
				{% csrf_token %} {% for field in form %}
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">
						{{ field.label }}
					</label>
					{{ field }} {% if field.errors %}
					<p class="text-red-500 text-sm mt-1">{{ field.errors|striptags }}</p>
					{% endif %}
				</div>
				{% endfor %}

				<button
					type="submit"
					class="px-6 py-2 bg-indigo-600 text-white rounded-lg"
				>
					Save
				</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

crud/templates/crud/post_detail.html
{% extends 'crud/base.html' %} {% block title %}Post Detail{% endblock %}
{%block content %} {% load static %}

<section class="max-w-4xl mx-auto px-6 py-12">
	<a
		href="{% url 'crud:post-list' %}"
		class="inline-block mb-6 text-white font-medium hover:underline"
	>
		← Back to posts
	</a>

	<article class="bg-white rounded-2xl shadow-lg overflow-hidden">
		{% if post.image %}
		<img
			src="{{ post.image.url }}"
			alt="{{ post.title }}"
			class="w-full h-96 object-cover"
		/>
		{% endif %}

		<div class="p-8">
			<div class="flex items-center text-sm text-gray-500 mb-4 space-x-2">
				<span>{{ post.created_at|date:"M d, Y" }}</span>
				<span>•</span>
				<span>By {{ post.author }}</span>
				<span>•</span>
				{% if request.user.is_authenticated %}
				<a href="{% url 'post-update' post.id %}" class="text-blue-500"
					>Update</a
				>
				<span>•</span>
				<a href="{% url 'post-delete' post.id %}" class="text-red-500"
					>Delete Post</a
				>
				{% endif %}
			</div>

			<h1 class="text-3xl md:text-4xl font-bold text-gray-800 mb-6">
				{{ post.title }}
			</h1>

			<div class="prose max-w-none text-gray-700 leading-relaxed">
				{{ post.description|linebreaks }}
			</div>
		</div>
	</article>
</section>

{% endblock %}

crud/templates/crud/post_list.html
{% extends "crud/base.html" %}{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<section class="max-w-7xl mx-auto px-6 py-12">
	<h1 class="text-3xl font-bold text-gray-800 mb-10">Latest Posts</h1>

	<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
		{% for post in posts %}
		<div
			class="bg-white rounded-2xl shadow-md overflow-hidden hover:shadow-xl transition"
		>
			<img
				src="{{ post.image.url }}"
				alt="{{ post.title }}"
				class="w-full h-48 object-cover"
			/>

			<div class="p-6">
				<span class="text-sm text-gray-500">
					{{ post.created_at|date:"M d, Y" }}
				</span>

				<h2 class="text-xl font-bold text-gray-800 mt-2 mb-3">
					{{ post.title }}
				</h2>

				<p class="text-gray-600 text-sm mb-4">
					{{ post.description|truncatechars:60 }}
				</p>

				<a
					href="{{post.get_absolute_url}}"
					class="text-indigo-600 font-semibold hover:underline"
				>
					Read more →
				</a>
				<p class="text-sm text-gray-500">By {{ post.author }}</p>
			</div>
		</div>
		{% empty %}
		<p class="text-gray-500">No posts found.</p>
		{% endfor %}
	</div>
</section>

  {% if is_paginated %}
<div class="flex justify-center mt-8">
  <nav class="inline-flex shadow-sm rounded-md">

    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}"
         class="px-3 py-2 border border-gray-300 bg-white text-gray-700 hover:bg-gray-100">
        Prev
      </a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <span
          class="px-4 py-2 border border-blue-600 bg-blue-600 text-white font-semibold">
          {{ num }}
        </span>
      {% else %}
        <a href="?page={{ num }}"
           class="px-4 py-2 border border-gray-300 bg-white text-gray-700 hover:bg-gray-100">
          {{ num }}
        </a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}"
         class="px-3 py-2 border border-gray-300 bg-white text-gray-700 hover:bg-gray-100">
        Next
      </a>
    {% endif %}

  </nav>
</div>
{% endif %}


{% endblock content %}

crud/templates/crud/post_update.html
{% extends "crud/base.html" %} {% block title %}Post Update{% endblock %}
{%block content %}
<div class="min-h-screen py-12">
	<div class="max-w-7xl mx-auto px-6">
		<div class="bg-gray-100 rounded-3xl shadow-xl p-8">
			<form method="post" enctype="multipart/form-data" class="space-y-6">
				{% csrf_token %} {% for field in form %}
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">
						{{ field.label }}
					</label>
					{{ field }} {% if field.errors %}
					<p class="text-red-500 text-sm mt-1">{{ field.errors|striptags }}</p>
					{% endif %}
				</div>
				{% endfor %}

				<button
					type="submit"
					class="px-6 py-2 bg-indigo-600 text-white rounded-lg"
				>
					Update
				</button>
				<a
					href="{{post.get_absolute_url}}"
					class="px-6 py-2 bg-gray-600 text-white rounded-lg"
				>
					Cancel
				</a>
			</form>
		</div>
	</div>
</div>

{% endblock %}

crud/templates/crud/warning.html
{% extends 'crud/base.html' %} {% block title %}Warning{% endblock %} 
{%block content %} {% load static %}

<div
	class="min-h-screen bg-slate-100 flex items-center justify-center px-4 py-12"
>
	<div class="bg-white rounded-3xl shadow-2xl p-10 max-w-md text-center">
		<!-- Warning Icon -->
		<div class="mb-6">
			<svg
				class="mx-auto h-12 w-12 text-red-600"
				xmlns="http://www.w3.org/2000/svg"
				fill="none"
				viewBox="0 0 24 24"
				stroke="currentColor"
			>
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M12 9v2m0 4h.01M12 5.25L2 21h20L12 5.25z"
				/>
			</svg>
		</div>

		<!-- Heading -->
		<h1 class="text-2xl font-bold text-gray-800 mb-4">Are you sure?</h1>

		<!-- Message -->
		<p class="text-gray-600 mb-8">
			Do you really want to delete the post "<span class="font-semibold"
				>{{ post.title }}</span
			>"? This action cannot be undone.
		</p>

		<!-- Buttons -->
		<div class="flex justify-center gap-4">
			<!-- Cancel -->
			<a
				href="{{ post.get_absolute_url }}"
				class="px-6 py-2 bg-gray-300 text-gray-800 font-semibold rounded-xl hover:bg-gray-400 transition"
			>
				Cancel
			</a>

			<!-- Confirm Delete -->
			<form method="post" class="">
				{% csrf_token %}
				<button
					type="submit"
					class="px-6 py-2 bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 transition"
				>
					Delete
				</button>
			</form>
		</div>
	</div>
</div>


{% endblock %}